#!/bin/bash

SHORTCUT_CMD="F"
SHORTCUT_CMD_PATH="${HOME}/.local/bin/${SHORTCUT_CMD}"
SHORTCUTS_MATCHES_FILE="${HOME}/.srgmatches"

TMP_FILENAME=''

display_shortcuts() {
    awk -v f_name=${TMP_FILENAME} -F':' '
    BEGIN {x=1};
    {
        if ($1 != f_name) {
            printf("\n%s\n", $1);
            f_name=$1;
        };
        printf("[%s] ", x);
        printf("%s", $2);
        for (i=3; i<= NF; i++) {
            printf(":%s", $i);
        }
        printf("\n");
        x++;
    };'
}

strip_colors() {
    sed -E "s/\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g"
}

format_shortcuts() {
    awk -F':' '
    {
        print $2 " " $1;
    };'
}

create_shortcut_cmd() {
    cat > "${SHORTCUT_CMD_PATH}" <<END
#!/bin/bash

MATCH=\$(sed -n "\$1p" < ${SHORTCUTS_MATCHES_FILE})
MATCH_LINE=\$(echo "\$MATCH" | cut -d" " -f1)
MATCH_FILE=\$(echo "\$MATCH" | sed 's/'"\$MATCH_LINE"' //')

# Determine the editor to use (default to vim)
EDITOR_STR="\${EDITOR:-vim}"

# Parse editor command into an array to handle arguments properly
read -ra EDITOR_CMD <<< "\$EDITOR_STR"

# Extract the base command name (remove path and get just the executable name)
EDITOR_NAME=\$(basename "\${EDITOR_CMD[0]}")

# Open the file with the appropriate syntax for each editor
case "\$EDITOR_NAME" in
    vim|vi|nvim|neovim)
        # vim, neovim: +line filename
        "\${EDITOR_CMD[@]}" +"\$MATCH_LINE" "\$MATCH_FILE"
        ;;
    nano|pico)
        # nano, pico: +line filename
        "\${EDITOR_CMD[@]}" +"\$MATCH_LINE" "\$MATCH_FILE"
        ;;
    emacs)
        # emacs: +line filename
        "\${EDITOR_CMD[@]}" +"\$MATCH_LINE" "\$MATCH_FILE"
        ;;
    code)
        # VS Code: --goto filename:line
        "\${EDITOR_CMD[@]}" --goto "\$MATCH_FILE:\$MATCH_LINE"
        ;;
    *)
        # Default fallback - try the +line syntax
        "\${EDITOR_CMD[@]}" +"\$MATCH_LINE" "\$MATCH_FILE"
        ;;
esac
END
    chmod +x "${SHORTCUT_CMD_PATH}"
}

rg --color=always --with-filename --line-number "$@" | tee >/dev/null >(display_shortcuts) >(strip_colors | format_shortcuts > "${SHORTCUTS_MATCHES_FILE}");

create_shortcut_cmd
